### ISSUE TITLE
How can I use the project with gradle?

### ISSUE THREAD

**Issue by Moyulingjiu** [mybatis/generator#1001]
Sorry, I'm a beginner in gradle and looking for some help. I used maven to build projects before, and I want to learn gradle recently. But I encountered a problem when using gradle to integrate mybatis generator.
The following is my configuration
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.10'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

group = 'top.beforedawn'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/spring/' }
    mavenLocal()
    mavenCentral()
}

configurations {
    mybatisGenerator
}

dependencies {
    // spring boot
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // validation
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '2.7.5'
    // lombok
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.26'
    // gson
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'
    // mysql
    implementation group: 'mysql', name: 'mysql-connector-java', version: '8.0.32'
    // mybatis
    implementation group: 'org.mybatis', name: 'mybatis', version: '3.5.13'
    // mybatis generator
    mybatisGenerator 'org.mybatis.generator:mybatis-generator-core:1.4.2'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('generateMyBatis', JavaExec) {
    classpath = configurations.mybatisGenerator
    mainClass = 'org.mybatis.generator.api.ShellRunner'
    args '--configfile', 'src/main/resources/generatorConfig.xml', '-overwrite'
}
```
It doesn't work when I run.

**Comment by Moyulingjiu** [comment]
I made sure my config file `src/main/resources/generatorConfig.xml` is correct. I have used in maven. It works.

**Comment by hazendaz** [comment]
Not sure how far you will get here with help considering we are entirely maven.  I would suggest going to out to gradle and looking through their documentation, maybe look at spring github or spring boot github as both are gradle.  Basically you need to try to focus in on those using gradle to see how they might achieve things.  This would not be an issue with our repo otherwise.

At least for myself, I personally don't care for gradle.  Few reasons why, first its just built on top of groovy so it lacks fact that groovy is unable to keep pace fast enough with java these days (it may allow kotlin now but personally feel the same, its still not directly java), and second it changes far too quickly lacking easy backwards compatibility.  On the second, I can point out numerous repos that are in bad states such as spotbugs as direct result.  Anyway that is my personal feelings and not a consensus in any way.

That said, unless you have a massively compelling reason, I would just stick to maven.  As you note, you are just wanting to learn it.  Yet in that regard, here you are on a maven based project team asking how to work with gradle :)  Maven is in fact addressing any reason in java space that gradle even exists making a move to it not really that important.

One other thing, if you intend to use latest stuff as seems indicated mostly in your build, use all latest, specifically, you used spring boot 2.7.5 and 2.7.10 and io.spring.dependency-management is still on very old spring style RELEASE they don't use any more.  Also you didn't indicate what gradle version, what java version, etc.

**Comment by jeffgbutler** [comment]
We don't publish a Gradle plugin for MyBatis generator. There are several such plugins out there, but I'm not familiar with their usage. You can find the plugins here: https://plugins.gradle.org/search?term=mybatis+generator. But again, these plugins are not published by our project and are not "official".

**Comment by Moyulingjiu** [comment]
> We don't publish a Gradle plugin for MyBatis generator. There are several such plugins out there, but I'm not familiar with their usage. You can find the plugins here: https://plugins.gradle.org/search?term=mybatis+generator. But again, these plugins are not published by our project and are not "official".

thanks
