### ISSUE TITLE
rootClass can not generate

### ISSUE THREAD

**Issue by pondered** [mybatis/generator#1032]
rootClass: BaseEntity use set method:
```java
    public BaseEntity setId(Long id) {
        this.id = id;
        return this;
    }
```

but  java.beans.Introspector#SET_PREFIX   use `(void.class.equals(resultType) && name.startsWith(SET_PREFIX))` so can't generate

I don't know which method to rewrite to modify return BaseEntity

i suppose override RootClassInfo but is private constaructor

**Comment by jeffgbutler** [comment]
Making the constructor public won't help you unless you plan to rewrite the bean introspector - which is not a good idea. The JavaBeans instrospector will not recognize this method as a setter because it doesn't follow the JavaBeans specification. But MyBatis will work with a "setter" method defined like this.

You could make a change to the `hasProperty` method in `RootClassInfo` so that it ignores the check for a proper setter. I'm not sure I want that in the official code base - I will have to think about that for a bit. But it should work if you want to try it in a local fork.

**Comment by pondered** [comment]
yes, i change `hasProperty` method, is work. thanks
