### ISSUE TITLE
MBG generate multiple BaseResultMap when suppressAllComments enabled

### ISSUE THREAD

**Issue by shapowang** [mybatis/generator#285]
Document of MBG said this :
MBG will automatically merge XML files if there is an existing file with the same name as the newly generated XML file. MBG will not overwrite any custom changes you make to the XML files it generates. You can run it over and over again without fear of losing custom changes to you XML. **MBG will replace any XML elements that were generated in a previous run.**
This is not true when we use 
`        <commentGenerator>
            <property name="suppressAllComments" value="true" />
        </commentGenerator>`
In the static function isGeneratedNode of XmlFileMergerJaxp.java,an xml node with out comment would be recorginized as non generated node.Run the generator twice would make the xml has two same node.The equality of new and old xml node should be done by compare the plain text .Please fix this.

**Comment by jeffgbutler** [comment]
The documentation clearly states that code merging will be disabled if you use the suppressAllComment property:

http://www.mybatis.org/generator/configreference/commentGenerator.html

Comparing plain text is unreliable.  This is working as designed.

**Comment by makesitgo** [comment]
@shapowang ... if you really need this feature, you could implement a plugin.

Hook into the `sqlMapDocumentGenerated(Document, IntrospectedTable)` phase.  Your goal here is to call `document.setRootElement` with the new desired, merged contents.

Implement however you see fit, I personally have had a lot of success by first creating a Document wrapper class that supported `org.w3c.Document` conversion to/from MBG's version.  You'd have a W3C document of the generated content, and could read from disk a W3C document of the existing content.  It's much easier to do manual merge's when comparing DOM nodes rather than raw text (as per @jeffgbutler's previous comment).  I even dug up some old code to help you out [here](https://gist.github.com/makesitgo/23dc69df5155018be3bafd5a1bc6a112)!

Once the merges are all complete, replace the document's root element with your new one and you should be good to go.

---

Of course, you could also choose to not include manual, hand-written code inside the same generated XML files.  Check out this [SO](https://stackoverflow.com/questions/19720102/mybatis-generator-whats-the-best-way-to-separate-out-auto-generated-and-han) that details an approach for supporting custom xml mappers alongside generated xml mappers.  This way, when you re-run MBG, all of your custom queries have no issues with potentially being overwritten.
