### ISSUE TITLE
1.3.6,how to remove  @Generated

### ISSUE THREAD

**Issue by Liesport758** [mybatis/generator#342]
how to remove @Generated.for example,
![image](https://user-images.githubusercontent.com/10843358/38848715-147f33a4-423b-11e8-8818-e354293c07a2.png)

**Comment by jeffgbutler** [comment]
If you specify "removeAllComments" in the comment generator configuration, it will remove the date and comments, but will leave the `@Generated` tag. I did this purposely because `@Generated` is now a part of the Java language so this is standard.  And honestly, many people are confused about the merge function which requires this support.

If you feel you absolutely must remove the annotation, then you can implement your own comment generator and not create the annotation.
