### ISSUE TITLE
haha...

### ISSUE THREAD

**Issue by piglingcn** [mybatis/generator#355]
Is there any way to generate only one baseExample and baseMapper through inheritance, and base.xml~~?

**Comment by jeffgbutler** [comment]
If I understand your question correctly, then no. Each generated example/mapper/xml is independent and self-contained. This was a conscious design choice because the generator was originally designed to output code with no dependencies. Each example class has to be able to generate SQL based solely on methods in the example class itself.  Therefore, the generated example classes are huge, hard to understand, and have quite a lot of duplicate code in them.

The new runtime for MyBatis Dynamic SQL resolves this problem by removing the example classes entirely - but also introducing an external dependency. IMHO this new way is far superior.
