### ISSUE TITLE
how can I generate @Mapper on dao interface?

### ISSUE THREAD

**Issue by kid1412621** [mybatis/generator#432]
When I set the targetRuntime to MyBatis3DynamicSql, it will generate. While I using MyBatis3, it's gone.
b.t.w If it is possible to generate @Repository .

**Comment by kid1412621** [comment]
@jeffgbutler OK, thanks. I'll try it out. 
And one more question, will mbg support non-xml config file? Nowadays XML is too heavy.

**Comment by jeffgbutler** [comment]
MBG configuration will probably continue to use XML as the default configuration format because XML parsing is built-in to the JDK. This allows MBG to have zero external dependencies. I can imagine a future module that would enable use of something like YAML. It would be relatively easy to parse YAML and build the MBG configuration objects. It's not on my TODO list right now, but maybe sometime in the future.

**Comment by fyeeme** [comment]
@gwokhou Thank you, you saved my time
