### ISSUE TITLE
if exist table picktype and pick_type, generat no expect

### ISSUE THREAD

**Issue by hackeryutu** [mybatis/generator#456]
if exist table picktype and pick_type generat
generat result: Filename is PickType, class name is Picktype
expect: have two class, Picktype and PickType.

**Comment by jeffgbutler** [comment]
This is happening because you are running the generator on a case insensitive file system. The generator will try to write files like PickType.java and Picktype.java - but the underlying file system sees those as the same file.

In your generator config you should rename the generated object for one of the tables like this:

```xml
    <table tableName="picktype" />
    <table tableName="pick_type" domainObjectName="PickTypeRenamed" />
 ```
