### ISSUE TITLE
How to automatically add @Repository annotation when generating map automatically

### ISSUE THREAD

**Issue by chenweibo** [mybatis/generator#479]
In IDEA like this 
@Autowired
     UserMapper userMapper 

will display a red warning. The online solution is to close the plugin. But adding @Repository to the map solves how to generate it automatically.

**Comment by jeffgbutler** [comment]
It would probably be better to configure IDEA so that it doesn't show these false positives - or you could just ignore it. A mapper is not a repository, so I don't think it's a good idea to add that annotation.

If you feel you must add the annotation, then you could write a generator plugin to do it.
