### ISSUE TITLE
how to set domainObjectName suffix in generateConfig.xml for mybatis generator.

### ISSUE THREAD

**Issue by kesa-Wu** [mybatis/generator#581]
`I encountered this situation:

table : t_user,t_manager,...

domainObjectName : UserEntity,ManagerEntity,...

I know how to replace the prefix using the domainObjectRenamingRule,

but how can i append the suffix?`

**Comment by kesa-Wu** [comment]
Can anyone commit an config example for this situation?

**Comment by jeffgbutler** [comment]
I added some comments to our discussion on Stack Overflow - I think I understand what the issue is and have the right answer now.

https://stackoverflow.com/questions/61628944/how-to-set-domainobjectname-suffix-in-generateconfig-xml-for-mybatis-generator

It's always a challenge to come up with a good regex!

**Comment by kesa-Wu** [comment]
<table tableName="%">
            <generatedKey column="id" sqlStatement="MySql" identity="true"/>
            <domainObjectRenamingRule searchString="(?i)^t(.*)" replaceString="$1Entity" />
        </table>

Thank you , it works fine now.
