### ISSUE TITLE
<properties> resource attribute doesn't work when using resource filtering

### ISSUE THREAD

**Issue by lingnanlu** [mybatis/generator#757]
I use **maven-resource-plugin**  to do resource filtering. But the config file doesn't recognize the filtered properties file. The file is really at the classpath.

the doc about the **resource** attribute says

> The qualified name of the property file. When specifying the resource, the classpath will be searched for the properties file. So a file specified as com/myproject/generatorConfig.properties must exist in the com.myproject package.

**Comment by jeffgbutler** [comment]
@lingnanlu - apologies for the delay in responding

This is probably happening because MyBatis generator runs in the `generate-sources` lifecycle phase and that phase runs before `process-resources` - which is where the filtering takes place. So I don't think this will ever work. It's the way Maven works so there's nothing we can do about it.

I assume you are passing properties into the configuration file. A better alternative is to reference the properties directly in the configuration file rather than through an intermediate property file.
