### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [mybatis/generator#803]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jeffgbutler** [comment]
Thanks for reaching out!

We are always open to new issues or pull requests with fixes, so that is one way to collaborate on a solution.

If you feel this issue is so impactful that it should be discussed privately before public disclosure, then you could create a private repository where we can collaborate and add me (@jeffgbutler) to it.

**Comment by JamieSlome** [comment]
@jeffgbutler - thanks for the response.

You can actually review the report privately here:

https://huntr.dev/bounties/acd74536-dea0-4507-8c2c-1df3e21a948a/

It is accessible to maintainers with repository write permissions.

**Comment by jeffgbutler** [comment]
@JamieSlome - please use one of the reporting mechanisms I outlined above. We don't want to utilize intermediate services.

Also wanted to let you know that all MyBatis projects are 100% volunteer efforts. We don't have any funding for bounties or any other type of payment.

**Comment by JamieSlome** [comment]
@ready-research - just a heads up on the request above ^

@jeffgbutler - we appreciate your time and wanted to make clear that we fund all of the bounties, and even reward maintainers for fixes as well 😄

**Comment by ready-research** [comment]
Hi @jeffgbutler, https://github.com/mybatis/generator/blob/f3907d3a4aad257e17ed3047bc4b089cdf5f92ca/eclipse/org.mybatis.generator.eclipse.ui/src/org/mybatis/generator/eclipse/ui/content/ConfigVerifyer.java#L99 makes use of SAXParser generated from a SAXParserFactory with no FEATURE_SECURE_PROCESSING set, allowing for XXE attacks.
```
        SAXParserFactory factory = SAXParserFactory.newInstance();
            factory.setValidating(false);
            SAXParser parser = factory.newSAXParser();        
            parser.parse(inputStream, this);
```

I opened a PR to fix this issue https://github.com/mybatis/generator/pull/806

**Comment by ready-research** [comment]
@JamieSlome Can you please validate this on behalf of the maintainer and also confirm the fix. Thanks.
https://github.com/mybatis/generator/pull/806#issuecomment-1015911381

**Comment by JamieSlome** [comment]
@ready-research - sorted ❤️ 

The report is now public and marked as fixed here:
https://www.huntr.dev/bounties/acd74536-dea0-4507-8c2c-1df3e21a948a/

Are you happy for us to publish a CVE against the report?

**Comment by jeffgbutler** [comment]
@JamieSlome this PR fixed an XXE vulnerability in the Eclipse plugin associated with MyBatis Generator. There is no XXE vulnerability in MyBatis Generator itself - only the plugin. The vulnerability could be activated by an interactive user in Eclipse right clicking on an XML file in an Eclipse project.

The discoverer of this vulnerability did not demonstrate any actual attack vector, and also did not test the initial pull request intended to fix the vulnerability. This was clear because the initial pull request actually broke the functionality of the plugin.

I'm not convinced this rises to the importance of a CVE. If you do publish anything about this, please make sure to make the distinction that this vulnerability is only in the Eclipse plugin.

**Comment by JamieSlome** [comment]
@jeffgbutler - thanks for the in-depth information.

Based on your description and reasoning, we will not publish the CVE! 🍰
