### ISSUE TITLE
Double-generate without clean the code will cause ...

### ISSUE THREAD

**Issue by tbwork** [mybatis/generator#82]
Double-generate (MBG for Eclipse + Java) without clean the code will cause methods of the generated interface definition be a functions with implement bodies like:
void function(){
}
rather than
void function();

**Comment by jeffgbutler** [comment]
I cannot reproduce this.  Can you give some details on how to make this happen?  Also, if you turn off the comment generator, then the Java merge function will fail - so please verify that you have not disabled the comment generator.

**Comment by MuhammadHuzaifah** [comment]
Hii jeffgButler,

here is Details about the MyBatisGenerator  generate without clean, it's happen when i register many table in configuration xml file. i've register 20 tables in the config file, the result is 2 files that generated by generator having duplicate ID, eg: id="BaseResultMap" -> has generate more then one times.

here is my generator config:

----start config ---
<table schema="public" tableName="t_rpt_00100" domainObjectName="Rpt00100">
            <property name="useActualColumnNames" value="false"/>
            
        </table>
        <table schema="public" tableName="t_rpt_00200" domainObjectName="Rpt00200">
            <property name="useActualColumnNames" value="false"/>
            
        </table>

        <table schema="public" tableName="t_rpt_00300" domainObjectName="Rpt00300">
            <property name="useActualColumnNames" value="false"/>
            
        </table>
        ...

       <table schema="public" tableName="t_rpt_09400" domainObjectName="Rpt09400">
            <property name="useActualColumnNames" value="false"/>
            
        </table>


---- end config ----


result XML Mapper XML in 2 files (Rpt00300Mapper.xml and Rpt01200Mapper.xml):
the result of 2 files mention before have a double generate ID and inconsistency, here is the result:

id="BaseResultMap" generate more than one times, --> both result XML file

and the inconsistency here:

<select id="countByExample" parameterType="com.fds.global.reporting.public.Rpt01200Example" resultType="java.lang.Integer">
    select count(*) from public.t_rpt_01000
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
  </select>

i've table t_rpt_01200, but SQL in the XML MAPPER file generated by generator select a public.t_rpt_01000 table, when the parameterType is Rpt01200Example.



Thankyou

**Comment by MuhammadHuzaifah** [comment]
> <select id="countByExample" parameterType="com.fds.global.reporting.public.Rpt01200Example" resultType="java.lang.Integer">
>     select count(*) from public.t_rpt_01000
>     <if test="_parameter != null">
>       <include refid="Example_Where_Clause" />
>     </if>
>   </select>

**Comment by MuhammadHuzaifah** [comment]
```
<select id="countByExample" parameterType="com.fds.global.reporting.public.Rpt01200Example" resultType="java.lang.Integer">
    select count(*) from public.t_rpt_01000
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
  </select>
```

**Comment by jeffgbutler** [comment]
@MuhammadHuzaifah - This sounds like a different issue than what was originally posted.  But it is troubling - I'll see if I can duplicate this.

**Comment by jeffgbutler** [comment]
@MuhammadHuzaifah - I've played around with this a bit.  One thing that stands out is that the package name "com.fds.global.reporting.public" is an invalid package name in Java (because it contains the keyword "public").  The eclipse plugin issues many warnings about this.

So I'm not sure how this happened.  But if you can reproduce it, please send some additional information:

1. Are you using the eclipse plugin, or just the generator standalone?
2. If you are using the eclipse plugin, are you seeing the warnings about an invalid name?
3. If you are using the standalone version, then no code merge is happening.  Do you have overwrite enabled?

If you can send a complete and consistent example of a failure, it would help to diagnose.  The code you sent above does not match the comments you made about it, so I'm really guessing about what the problem might be.

**Comment by jeffgbutler** [comment]
No response.  Feel free to re-open if you can provide a reproducible test case.

**Comment by CallMeXYZ** [comment]
it comes me to that mapper merging just append the same content to the current `<mapper>` when re-generating

**Comment by MuhammadHuzaifah** [comment]
@jeffgbutler i'am so sorry can't reply. 

here is the problem that i've found. i am using stand alone mybatis generator using commandline java -jar mybatis-generator (bla bla bla)

the first attemp generated perfectly, no problem.
then when i've running the second command using --overwrite parameter (the first generate command i've put the overwrite parameter too), result for the XML MAPPER have append like @CallMeXYZ  said. i use mybatis generator version 1.3.2, even i changed to version 1.3.5 that problem is the same.

**Comment by jeffgbutler** [comment]
@CallMeXYZ and @MuhammadHuzaifah  Do you have the comment generator configured with suppressAllComments=true?

**Comment by MuhammadHuzaifah** [comment]
@jeffgbutler Yes Jeff, i put this 
        <commentGenerator>
            <property name="suppressAllComments" value="true" />
        </commentGenerator>
in my config

**Comment by CallMeXYZ** [comment]
@jeffgbutler yep~i guess the generator use the comment to determine overwriting or not,right?

**Comment by jeffgbutler** [comment]
OK - makes sense to me.  If you suppress all comments, then code merging is disabled.  The generator uses the comments to determine what can be deleted.  If you are trying to avoid extra source control commits when things haven't really changed, then use this:

```xml
<commentGenerator>
  <property name="suppressDate" value="true"/>
</commentGenerator>
```
