### ISSUE TITLE
is it possible to support postgresql jsonb

### ISSUE THREAD

**Issue by jiangxiaoqiang** [mybatis/generator#841]
I know we could implement a custom handler to support jsonb, but it will modify the code every time, is it possible to support postgresql jsonb original? this is the error ouput:

```
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: column "tags" is of type jsonb but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 541
### The error may exist in class path resource [mybatis/mapper/dolphin/RssSubSourceMapper.xml]
### The error may involve com.dolphin.soa.post.dao.RssSubSourceMapper.updateByPrimaryKeySelective-Inline
### The error occurred while setting parameters
### SQL: UPDATE rss_sub_source SET sub_url = ?, created_time = ?, updated_time = ?, sub_status = ?, rss_type = ?, standard_type = ?, standard_version = ?, cron = ?, trigger_count = ?, next_trigger_time = ?, sub_name = ?, last_trigger_time = ?, intro = ?, failed_count = ?, frequency_month = ?, reputation = ?, rep_latest_refresh_time = ?, scrapy_take_time = ?, censor_status = ?, etag = ?, last_modified = ?, editor_pick = ?, fav_icon_url = ?, dynamic_interval = ?, local_icon_url = ?, creator = ?, tags = ? WHERE id = ?
### Cause: org.postgresql.util.PSQLException: ERROR: column "tags" is of type jsonb but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.

```

**Comment by jeffgbutler** [comment]
It depends on which runtime you are using. If you are using the runtime for MyBatis Dynamic SQL, then there is support for making PostgeSQL JSON processing easier. You can see the test here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/custom_render

I like this solution because it can be implemented with a one line change in the generated code (using a custom rendering strategy). It would be relatively easy to change the generator to support this with a column override.

If you are using the old legacy runtime in MyBatis Generator - `targetRuntime=MyBatis3` - things are more difficult. That runtime is essentially deprecated and I don't think we'll make significant changes for it.

**Comment by jiangxiaoqiang** [comment]
> It depends on which runtime you are using. If you are using the runtime for MyBatis Dynamic SQL, then there is support for making PostgeSQL JSON processing easier. You can see the test here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/custom_render
> 
> I like this solution because it can be implemented with a one line change in the generated code (using a custom rendering strategy). It would be relatively easy to change the generator to support this with a column override.
> 
> If you are using the old legacy runtime in MyBatis Generator - `targetRuntime=MyBatis3` - things are more difficult. That runtime is essentially deprecated and I don't think we'll make significant changes for it.

Thank you for your patient, I will tried to using the dynamic sql.
