### ISSUE TITLE
Provide an option to disable -*withBlob- for a specific table

### ISSUE THREAD

**Issue by ChristianLutz** [mybatis/generator#930]
In our db model we have a table containing several column with `varbinary(4)`. This binaries are required and the generated object isn't valid without them.  I have disabled the generation of separate blob models with `<context defaultModelType="flat">`. In this scenario I would like to disable all `*withBlobs` methods for a specific table, too. Otherwise it would be miss leading and the generation of an invalid object would be possible.

**Comment by jeffgbutler** [comment]
It looks like you are using the older deprecated runtime `<context targetRuntime="MyBatis3">`. In the newer runtimes, the model type is always flat, and there are no separate "WithBlobs" methods (and the generated code is much better too!). So you might try the newer runtime and see if it's closer to what you want.

In the old runtime, you could write a simple plugin that disables the "WithBlobs" methods. If you do that, then you won't be able to access the BLOB fields. So I'm wondering if you want to also change the non-blobs methods so that they include all columns. For example, "updateByPrimaryKeyWithBlobs" is disabled and "updateByPrimaryKey" is changed to include all columns. You could also do that in a plugin, but it is more complex (you could disable "updateByPrimaryKey", then rename "updateByPrimaryKeyWithBlobls" -> "updateByPrimaryKey").

**Comment by ChristianLutz** [comment]
@jeffgbutler Hello, yes your are right. Thx for pointing out that the newer runtime is capable of this. We will migrate to the newer version next year. So I'll close this. Thank you.
